### ISSUE TITLE
Chest Tracker not detecting items inside Shulkers

### ISSUE THREAD

**Issue by TheSrBig** [JackFred2/ChestTracker#205] opened 2024-08-15 20:12 UTC
I've encountered an issue when trying to track specific items stored inside Shulker Boxes. The problem is as follows:

When I search for a specific item, like "experience bottles," that I know are stored inside Shulker Boxes, the mod doesn’t show me where those Shulker Boxes are located. Even though I’m certain that some Shulkers in my inventory or chests contain these items, the mod fails to identify their location.

**Steps to reproduce:**

1. Place experience bottles inside several Shulker Boxes.
2. Store these Shulker Boxes in a chest.
3. Use the Chest Tracker mod to search for "experience bottles."
4. Notice that the mod does not indicate the location of the Shulker Boxes containing the experience bottles.

**Expected behavior:**

The mod should correctly track the experience bottles, showing which Shulker Boxes contain them and where those Shulker Boxes are located.

**Actual behavior:**

The mod fails to display any information about the Shulker Boxes containing the experience bottles, making it difficult to locate items stored within them.

**Comment by poopycarti** [comment] 2024-08-16 00:55
Having the same issue, tho i can search glass but it doesnt show the correct amount, only the location

**Comment by JackFred2** [comment] 2024-08-16 01:02
Known issue and duplicate of #195; already have a plan for this.

**Closed as not planned** 2024-08-16 01:02 UTC
Labels: duplicate, enhancement
