### ISSUE TITLE
optifine conflict

### ISSUE THREAD

**Issue by YinNue** [JackFred2/ChestTracker#18] opened 2021-03-20 09:09 UTC
Running on Fabric under 1.16.4, it will conflict with optfine. I don't know if other versions are like this. When I only open optfine and chesttrack, the light and shadow screen will become all white or all black, because I didn't test it. After other versions, even if I change the optfine version, the same is true. If I can, please fix this problem, and there is also a conflict with modmenu.

**Comment by JackFred2** [comment] 2021-03-20 13:02
Could I get a list of mods and the mod versions/shaders used? Can't reproduce any errors on 1.16.5 with optifine and latest chesttracker version, and i can enter the config with modmenu fine.

![image](https://user-images.githubusercontent.com/8350692/111870354-326ebc00-897c-11eb-8684-9f058b305d00.png)

**Comment by JackFred2** [comment] 2021-07-15 01:34
Will close this for now, if shaders start having issues on current versions feel free to make a new issue.

**Closed by JackFred2** 2021-07-15 01:34 UTC
Labels: bug, moreinfo
