### ISSUE TITLE
[Suggestion] Ignore specified named containers

### ISSUE THREAD

**Issue by Art0sh** [JackFred2/ChestTracker#215] opened 2024-08-30 20:34 UTC
I want to suggest to add an option that let you set names of containers that should not be saved, even if settings are set to saving all containers automatically.
I had the idea after I had around 200 saved containers that were saved on random blocks like dirt, trees and walls when I used 
"/enderchest" or other commands that opened a "clickable inventory gui".
![30 08_22 33 _7b8d4b8](https://github.com/user-attachments/assets/6759bb63-bbb6-43dd-b759-eb9d134001c9)

**Comment by JackFred2** [comment] 2024-09-02 19:27
Duplicate of #212

**Closed as not planned by JackFred2** 2024-09-02 19:27 UTC
Labels: duplicate, enhancement
